# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: VS2017-Win2016

steps:
- bash: |
   if [ -f extensions.csproj ]
   then
       dotnet build extensions.csproj --output ./bin
   fi
  displayName: 'Build extensions'

- task: NodeTool@0
  displayName: 'Use Node version 14.x'
  inputs:
    versionSpec: 14.x

- task: Npm@1
  displayName: 'Install Application Dependencies'
  inputs:
    workingDir: '$(System.DefaultWorkingDirectory)/func-app-refresh'
    verbose: false
    
- task: Npm@1
  displayName: 'Install Common Dependencies'
  inputs:
    workingDir: '$(System.DefaultWorkingDirectory)/common'
    verbose: false

- task: Npm@1
  displayName: 'Run ''build'' script'
  inputs:
    command: custom
    workingDir: '$(System.DefaultWorkingDirectory)/func-app-refresh'
    verbose: false
    customCommand: 'run build --if-present'

- task: Npm@1
  displayName: 'Remove extraneous packages'
  inputs:
    command: custom
    workingDir: '$(System.DefaultWorkingDirectory)/func-app-refresh'
    verbose: false
    customCommand: 'prune --production'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/func-app-refresh'
    archiveFile: '$(Build.ArtifactStagingDirectory)/func-app-refresh-$(Build.BuildId).zip' 
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'